services:
  # Container cho Database MySQL
  mysql-db:
    image: mysql:8.0
    container_name: qr_attendance_db
    # Ép server dùng chuẩn unicode_ci để khớp với script seed
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: qr_attendance_dev
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Container cho Redis
  redis-cache:
    image: redis:7-alpine
    container_name: qr_attendance_redis
    ports:
      - "6379:6379"

  mailpit:
    image: axllent/mailpit
    container_name: qr_attendance_mailpit
    ports:
      - "1025:1025" # Cổng SMTP để Backend gửi mail vào
      - "8025:8025" # Cổng Web UI để vào xem mail (như Gmail)

  # Container cho Spring Boot Backend
  backend-app:
    build:
      context: "./backend springboot"
      dockerfile: Dockerfile
    container_name: qr_attendance_backend
    ports:
      - "0.0.0.0:8081:8081"
    depends_on:
      mysql-db:
        condition: service_healthy
      redis-cache:
        condition: service_started
    environment:
      - SERVER_PORT=8081
      - SERVER_ADDRESS=0.0.0.0
      # KHÔI PHỤC LẠI: Thêm connectionCollation vào cuối để đồng bộ 100% với DB
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/qr_attendance_dev?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATA_REDIS_HOST=redis-cache
      - SPRING_DATA_REDIS_PORT=6379

      # --- FIX LỖI EMAIL ---
#      - SPRING_MAIL_HOST=smtp.gmail.com
#      - SPRING_MAIL_PORT=587
#      - SPRING_MAIL_USERNAME=your-email@gmail.com
#      - SPRING_MAIL_PASSWORD=your-app-password
#      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
#      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true

      # cấu hình Mail để trỏ vào Mailpit
      - SPRING_MAIL_HOST=mailpit
      - SPRING_MAIL_PORT=1025
      - SPRING_MAIL_USERNAME=
      - SPRING_MAIL_PASSWORD=
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=false
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=false

volumes:
  db_data: