server:
  port: 8081

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  datasource:
    url: jdbc:mysql://localhost:3306/qr_attendance_dev?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci
    username: root
    password: 123456
    hikari:
      connection-init-sql: SET time_zone = '+00:00'

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3s

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:db/seed
    baseline-on-migrate: false
    validate-on-migrate: true

logging:
  level:
    org.flywaydb: INFO
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security: info

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

app:
  jwt:
    issuer: "attendance-api-dev"
    secret: "CHANGE_ME_DEV_32_CHARS_MINIMUM_SECRET"
    accessTokenMinutes: 15
    refreshTokenDays: 30

  auth:
    password-reset:
      token-minutes: 30
      frontend-reset-url: "http://localhost:5173/reset-password"
      rate-limit:
        redis-key-prefix: "auth:password-reset:rl:dev"
        window-minutes: 60
        max-requests-per-email: 3
        max-requests-per-ip: 20
        fail-open: true

    email-outbox:
      encryption-key-base64: "n7Jw7GmD2xg4g4o9nHc4k0bqQ5nG5H1o0i4m5Yw1M9Q="

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings